name: CI Self Hosted

on: [push]

env:
  IMAGE_NAME: nhkwardana30/cicd-githubnew
  CONTAINER_NAME: service-backend-1
  REGISTRY: docker.io

jobs:
  build-and-push:
    runs-on: [self-hosted, linux]

    steps:
    - name: start Discord
      run: |
        curl -H "Content-Type: application/json" \
        -d '{
          "username": "GitHub Actions",
          "embeds": [{
            "title": "...............CI/CD START................",
            "color": 3066993,
            "fields": [
              {"name": "Repository", "value": "'"${{ github.repository }}"'", "inline": true},
              {"name": "Branch", "value": "'"${{ github.ref_name }}"'", "inline": true},
              {"name": "Workflow", "value": "'"${{ github.workflow }}"'"}
            ]
          }]
        }' \
        ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t $REGISTRY/${{ env.IMAGE_NAME }}:latest .

    - name: Push image to DockerHub
      run: docker push $REGISTRY/${{ env.IMAGE_NAME }}:latest

    - name: Create SSH key file
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: SSH Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
          echo "Logging into DockerHub..."
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

          echo "Pulling latest image..."
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/cicd-githubnew:latest

          echo "Stopping & removing old container..."
          docker stop service-backend-1 || true
          docker rm service-backend-1 || true

          echo "Running new container..."
          docker run -d --name service-backend-1 -p 4000:4000 ${{ secrets.DOCKERHUB_USERNAME }}/cicd-githubnew:latest
        EOF


    - name: Notify Discord (Success)
      if: success()
      run: |
        curl -H "Content-Type: application/json" \
        -d '{
          "username": "GitHub Actions",
          "embeds": [{
            "title": "✅ CI/CD SUCCESS",
            "color": 3066993,
            "fields": [
              {"name": "Repository", "value": "'"${{ github.repository }}"'", "inline": true},
              {"name": "Branch", "value": "'"${{ github.ref_name }}"'", "inline": true},
              {"name": "Commit", "value": "'"${{ github.sha }}"'"}
            ]
          }]
        }' \
        ${{ secrets.DISCORD_WEBHOOK_URL }}

    - name: Notify Discord (Failure)
      if: failure()
      run: |
        curl -H "Content-Type: application/json" \
        -d '{
          "username": "GitHub Actions",
          "embeds": [{
            "title": "❌ CI/CD FAILED",
            "color": 15158332,
            "fields": [
              {"name": "Repository", "value": "'"${{ github.repository }}"'", "inline": true},
              {"name": "Branch", "value": "'"${{ github.ref_name }}"'", "inline": true},
              {"name": "Workflow", "value": "'"${{ github.workflow }}"'"}
            ]
          }]
        }' \
        ${{ secrets.DISCORD_WEBHOOK_URL }}
